spring:
  #数据源
  datasource:
    #1.JDBC
    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver  # 驱动程序通过SPI自动注册，通常不需要手动加载驱动程序类。
    url: jdbc:mysql://localhost:3306/aiwriter?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: s546449346
    druid:
      #2.连接池配置
      #初始化连接池的连接数量 大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      #配置获取连接等待超时的时间
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      # 是否缓存preparedStatement，也就是PSCache  官方建议MySQL下建议关闭   个人建议如果想用SQL防火墙 建议打开
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filter:
        stat:
          merge-sql: true
          slow-sql-millis: 5000
      #3.基础监控配置
      web-stat-filter:
        enabled: true
        url-pattern: /*
        #设置不统计哪些URL
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        session-stat-enable: true
        session-stat-max-count: 100
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        #设置监控页面的登录名和密码
        login-username: admin
        login-password: admin
        allow: 127.0.0.1
        #deny: 192.168.1.100
#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#显示日志
logging:
  level:
    com.hdumil.aiwriter.back.mapper: debug

#百度API的密匙
baiduAPI:
  NLP:
    appId: 25555521
    apiKey: d0ZmMHyBgj9S3FiWkGZEXCMV
    secretKey: 4nPsqIPZIAPMntaF2BomhEGGdtiGSxwy
  Retrieval:
    appId: 25555528
    apiKey: eHltBclr7s1kbGiSRQlvz1PY
    secretKey: gDWzGQljWFsa5uuTzgd3TGxVp0GyLlUg
  Customized:
    appId: 25555528
    apiKey: eHltBclr7s1kbGiSRQlvz1PY
    secretKey: gDWzGQljWFsa5uuTzgd3TGxVp0GyLlUg
  Review:
    appId: 25555527
    apiKey: rWKKOKTAcov73GpTRZkGu9zF
    secretKey: Omas1jvYGTsQYOd45nETzpZmqlwNHEdx
  SearchAuthorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwidXNlcl9pZCI6OSwianRpIjoiODUxNThjMzIyNzU0NDQyM2FhMWEyZmE3YWQzNjAxNzciLCJleHAiOjE4Njc2NDc0NzN9.w71rTW_aBb7G4B-Xq4q5YiFlIH4oqWpYjq93gtAclZU
